### ISSUE TITLE
nt working

### ISSUE THREAD

**Issue by voidbozo** [OddDevelopment/OperaGX-Nitro-Gen#10]
it syas uh oh looks like uve already claimed a gift even tho i dint

**Comment by NotClavilux** [comment]
Elaborate

**Comment by d-Dice** [comment]
They patched it, after generating a promo it'll say "Looks like you already claimed a gift.". And no, it's not because I had nitro on the account before. Could be related to the partner ID or they added something else

**Comment by NotClavilux** [comment]
> They patched it, after generating a promo it'll say "Looks like you already claimed a gift.". And no, it's not because I had nitro on the account before. Could be related to the partner ID or they added something else

I see, for me it could possibly be because i already had nitro, not on the alt i tried to redeem it on tho, maybe it's related to the ip?

**Comment by d-Dice** [comment]
> > They patched it, after generating a promo it'll say "Looks like you already claimed a gift.". And no, it's not because I had nitro on the account before. Could be related to the partner ID or they added something else
> 
> I see, for me it could possibly be because i already had nitro, not on the alt i tried to redeem it on tho, maybe it's related to the ip?

Tried vpn but same thing. Maybe proxies are required now. I will buy some and test

**Comment by NotClavilux** [comment]
> > > They patched it, after generating a promo it'll say "Looks like you already claimed a gift.". And no, it's not because I had nitro on the account before. Could be related to the partner ID or they added something else
> > 
> > 
> > I see, for me it could possibly be because i already had nitro, not on the alt i tried to redeem it on tho, maybe it's related to the ip?
> 
> Tried vpn but same thing. Maybe proxies are required now. I will buy some and test

Any progress?

**Comment by OddDevelopment** [comment]
> They patched it, after generating a promo it'll say "Looks like you already claimed a gift.". And no, it's not because I had nitro on the account before. Could be related to the partner ID or they added something else

We already randomize the partner ID so it should work fine

**Comment by d-Dice** [comment]
> > > > They patched it, after generating a promo it'll say "Looks like you already claimed a gift.". And no, it's not because I had nitro on the account before. Could be related to the partner ID or they added something else
> > > 
> > > 
> > > I see, for me it could possibly be because i already had nitro, not on the alt i tried to redeem it on tho, maybe it's related to the ip?
> > 
> > 
> > Tried vpn but same thing. Maybe proxies are required now. I will buy some and test
> 
> Any progress?

The account was flagged. Made another new account and worked
