### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by basilisk6969** [OddDevelopment/OperaGX-Nitro-Gen#11]
showing "nuh uh" something went wrong..

**Comment by basilisk6969** [comment]
when i get the nitro promo code and run it shows here claim your nitro then "nuh uh something went wrong" smthing

**Comment by OddDevelopment** [comment]
Can you please send a screenshot of this.

**Comment by basilisk6969** [comment]
![Screenshot 2024-01-13 201332](https://github.com/OddDevelopment/OperaGX-Nitro-Gen/assets/156439715/130ff2b8-0911-48b9-86c3-07f3b04e762d)
here

**Comment by OddDevelopment** [comment]
This means you dont meet discords requirements https://support.discord.com/hc/en-us/articles/19822382831767-1-Month-Discord-Nitro-for-Opera-GX-Users-2023-Promo-FAQ please read this article. Not a problem with the gen.
