### ISSUE TITLE
How do i get the codes

### ISSUE THREAD

**Issue by 0SVPanda** [OddDevelopment/OperaGX-Nitro-Gen#13]
Where do the codes show up one I run the script?

**Comment by zaiah223** [comment]
I have the same exact question. I keep getting the "Token saved to codes.txt file." but cannot find the file even when searching for it through my file explorer...

**Comment by NorthernChicken** [comment]
where are you running the script? In a code editor or the terminal?

**Comment by RobPYDeveloper** [comment]
> Where do the codes show up one I run the script?

Hey bro. u can have my already generated codes:
https://discord.com/billing/promotions/qBg72CRcMutxz24NnEgAgr4G
(if doesn't work means i already got it)

**Comment by OddDevelopment** [comment]
It will be in a file called "codes.txt" in the same folder you ran the script in.
