### ISSUE TITLE
Can't find the "codes.txt" file.

### ISSUE THREAD

**Issue by RobPYDeveloper** [OddDevelopment/OperaGX-Nitro-Gen#15]
Hey there's a similiar problem like the other one but...

**I CAN'T FIND THE CODES.TXT**

I thought it gonna create a txt, ok then, but.. where is it?
I'm running it on terminal 

![problem image](https://github.com/OddDevelopment/OperaGX-Nitro-Gen/assets/144294349/d3dd6c59-ab60-4247-8eee-40c71aeb5d4b)

**Comment by OddDevelopment** [comment]
Can you send a screenshot of the folder where the index.js file is and all the other files?

**Comment by RobPYDeveloper** [comment]
here
![problem folder](https://github.com/OddDevelopment/OperaGX-Nitro-Gen/assets/144294349/da43a0c7-88aa-4e70-92ed-d2951860ce9f)

**Comment by RobPYDeveloper** [comment]
there's no index.js tho

**Comment by OddDevelopment** [comment]
Yeah sorry im used to working with javascript, Can you try checking your main directory for your user? Sometimes it might default to there.

**Comment by RobPYDeveloper** [comment]
![directory](https://github.com/OddDevelopment/OperaGX-Nitro-Gen/assets/144294349/44ce99bd-5956-45f1-8956-41d328b9c644)
here

**Comment by OddDevelopment** [comment]
Works for everyone else, Might be your PC is write only I would recommend running it on replit so you dont need to worry about file systems.
