### ISSUE TITLE
An error occurred: HTTPSConnectionPool

### ISSUE THREAD

**Issue by Maverick6875** [OddDevelopment/OperaGX-Nitro-Gen#23]
An error occurred: HTTPSConnectionPool(host='api.discord.gx.games', port=443): Max retries exceeded with url: /v1/direct-fulfillment (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f3f5e38e560>: Failed to resolve 'api.discord.gx.games' ([Errno -2] Name or service not known)"))

**Comment by FurkanBeyCode** [comment]
I had the same problem.

**Comment by NorthernChicken** [comment]
I seem to be having this issue as well. It appears the server "api.discord.gx.games" is no longer available, likely because the promotional is over. Trying to ping the server also doesn't work. Sorry, but I don't think anything can be done about this since the OperaGX/discord promotional has ended.

**Comment by Maverick6875** [comment]
i think so also

**Comment by t-mole** [comment]
Unless it ended early, the promo is supposed to go until June 17th...

**Comment by d-Dice** [comment]
https://discord.opr.gg/v2/direct-fulfillment ?
