### ISSUE TITLE
i got a issue 

### ISSUE THREAD

**Issue by Harshdeep72** [OddDevelopment/OperaGX-Nitro-Gen#4]
so when i started  the gen it did generated some promos but when i tried to redeem promos it showed me this https://pasteboard.co/l84ahZIiyS3K.png

**Comment by NorthernChicken** [comment]
A lot of the links this generates will already have been claimed, you have to keep generating until you get a link that works.

**Comment by OddDevelopment** [comment]
This is not an issue with the code its discord thinking your account is suspicious/had nitro in the past, Try doing the promo manually by downloading the browser and I guarantee you'll have the same issue.

**Comment by OddDevelopment** [comment]
Never mind looks like a patch, Looking into.

**Comment by Harshdeep72** [comment]
will you be reposting this gen with updates ?

**Comment by OddDevelopment** [comment]
@Harshdeep72 Yes, I will continue to update it until the promo ends.

**Comment by Harshdeep72** [comment]
well the update you did didnt worked

**Comment by NorthernChicken** [comment]
delete codes.txt and run again. You may be using old codes by accident.

**Comment by andi-l** [comment]
Do the promotion codes still work? I'm trying multiple codes and I always just get 'Oh oh! Looks like something went wrong.' On fresh new accounts and older accounts.
